.\" Man-based Cheatsheet for Rust Programming Language
.\" Send an issue on the github page to correct errors/tpos

.TH Rust-Cheatsheet 7 "01 March 2025" "1.0" "Rust Programming Language Cheatsheet"

.SH NAME
Rust Installation

.SH SYNOPSIS
.B Install Page
.br
	https://www.rust-lang.org/tools/install
.br

.B Rustup - Mac Homebrew - Install
.br
From Terminal:
.br
	brew install rust
.br

Formula:
.br
	https://formulae.brew.sh/formula/rust
.br

.B Rustup - Linux/Mac - Install
.br
From Terminal:
.br
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
.br

.B Rustup - Linux/Mac - Uninstall
.br
rustup self uninstall
.br

.B Rustup - Windows - Install
.br
https://www.rust-lang.org/tools/install
.br

Description:
.br
	Download rustup installer from the official download page.


.SH SEE ALSO
Original Content (Requires Javascript):
.br
https://speedsheet.io/s/rust

.SH AUTHOR
Original Contents by Graydon Hoare
.br
Transcribed to Man pages by J.Leonard
