.\" Man-based Cheatsheet for Rust Programming Language
.\" Send an issue on the github page to correct errors/tpos

.TH Rust-Cheatsheet 7 "01 March 2025" "1.0" "Rust Programming Language Cheatsheet"

.SH NAME
Rust Environment Variable - Cargo Home

.SH SYNOPSIS
.B Cargo Home
.br
CARGO_HOME
.br

Description:
.br
	Locates the Cargo directory
.br

	Typically:
.br
		$HOME/.cargo
.br

.B Rustup Home
.br
RUSTUP_HOME
.br

Description:
.br
	Locates the Rustup directory.
.br

	Typically:
.br
		$HOME/.rustup

.SH SEE ALSO
Original Content (Requires Javascript):
.br
https://speedsheet.io/s/rust

.SH AUTHOR
Original Contents by Graydon Hoare
.br
Transcribed to Man pages by J.Leonard
